[package]
name = "knot-jit"
version.workspace = true
edition.workspace = true

[lib]
crate-type = ["rlib"]

[dependencies]
knot = { workspace = true }
knot-compiler = { workspace = true }
knot-runtime = { workspace = true }
cranelift-codegen = { workspace = true }
cranelift-frontend = { workspace = true }
cranelift-module = { workspace = true }
cranelift-jit = { workspace = true }
cranelift-native = { workspace = true }
libc = { workspace = true }
